// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: Replace the placeholder values below with your actual Firebase configuration.
/// You can get these values from the Firebase Console:
/// 1. Go to https://console.firebase.google.com/
/// 2. Select your project
/// 3. Go to Project Settings > General tab
/// 4. Scroll down to "Your apps" section
/// 5. Click on your app to see the configuration
///
/// Or use the Firebase CLI to generate this file automatically:
/// ```bash
/// npm install -g firebase-tools
/// firebase login
/// flutterfire configure
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0123456789abcdef', // Replace with your web API key
    appId: '1:123456789:web:abcdef123456', // Replace with your web app ID
    messagingSenderId: '123456789', // Replace with your sender ID
    projectId: 'free-image-genie', // Replace with your project ID
    authDomain:
        'free-image-genie.firebaseapp.com', // Replace with your auth domain
    storageBucket:
        'free-image-genie.appspot.com', // Replace with your storage bucket
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0123456789abcdef', // Replace with your Android API key
    appId:
        '1:123456789:android:abcdef123456', // Replace with your Android app ID
    messagingSenderId: '123456789', // Replace with your sender ID
    projectId: 'free-image-genie', // Replace with your project ID
    storageBucket:
        'free-image-genie.appspot.com', // Replace with your storage bucket
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0123456789abcdef', // Replace with your iOS API key
    appId: '1:123456789:ios:abcdef123456', // Replace with your iOS app ID
    messagingSenderId: '123456789', // Replace with your sender ID
    projectId: 'free-image-genie', // Replace with your project ID
    storageBucket:
        'free-image-genie.appspot.com', // Replace with your storage bucket
    iosBundleId:
        'com.img.free_image_genie', // Make sure this matches your iOS bundle ID
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0123456789abcdef', // Replace with your macOS API key
    appId: '1:123456789:macos:abcdef123456', // Replace with your macOS app ID
    messagingSenderId: '123456789', // Replace with your sender ID
    projectId: 'free-image-genie', // Replace with your project ID
    storageBucket:
        'free-image-genie.appspot.com', // Replace with your storage bucket
    iosBundleId:
        'com.img.free_image_genie', // Make sure this matches your macOS bundle ID
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0123456789abcdef', // Replace with your Windows API key
    appId: '1:123456789:web:abcdef123456', // Replace with your Windows app ID
    messagingSenderId: '123456789', // Replace with your sender ID
    projectId: 'free-image-genie', // Replace with your project ID
    authDomain:
        'free-image-genie.firebaseapp.com', // Replace with your auth domain
    storageBucket:
        'free-image-genie.appspot.com', // Replace with your storage bucket
  );
}
